### PR TITLE
Update Packet24MobSpawn.java

### PR DESCRIPTION
**Pull request by caojohnny**
Fixed cast to byte for an int field while assigning a value to int b.

### CODE REVIEW

**Comment by caojohnny** [comment]
Never mind... Found out how.

**Comment by Wolvereness** [comment]
No.

**Comment by caojohnny** [comment]
Okay D:

Why may I ask

**Comment by natemort** [comment]
@AgentTroll We don't do PR's to mc-dev.  Mc-dev is a decompiled version of minecraft, so if it isn't that way in mc-dev, then it isn't that way in minecraft.  As such, changing mc-dev doesn't make sense.

**Comment by caojohnny** [comment]
@evilmidget38 True, but does a byte cast really make sense to an int field? Sorry if I'm a bother or being really obscure but I'm just curious how minecraft can have such a stupid mistake as this.

**Comment by natemort** [comment]
@AgentTroll We don't change mc-dev, regardless of whether or not the code makes sense.  This repo is nothing more than the result of applying our mappings to minecraft and decompiling it.

If something needs to be changed, it's changed in the CraftBukkit repo, so PR's should be made there instead.  This change in particular, however, is an unnecessary diff and isn't justified.

**Comment by caojohnny** [comment]
@evilmidget38 thanks. That clears up a few things.

**Pull request closed without merging**
