### PR TITLE
Spelling error

### PR DESCRIPTION
**Pull request by prayerie**

### CODE REVIEW

**Comment by caojohnny** [comment]
....

Have you read all of the other PRs?

**Comment by tonybruess** [comment]
#5 #7 #9

**Comment by Alexandre2006** [comment]
Wow this is old.

**Comment by Alexandre2006** [comment]
Duplicate of #13

**Comment by ghost** [comment]
Hi

**Comment by prayerie** [comment]
> Hi

thanks for reminding me to close this stupid PR I made

**Pull request closed without merging**
